### PR TITLE
Make bird aware of device routes for all non-calico interfaces

### LINKED ISSUE #122: Calico node does not use the correct interface
We use vagrant to run docker, each vagrant node has two interfaces:

```
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:2b:f6:46 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 83894sec preferred_lft 83894sec
    inet6 fe80::a00:27ff:fe2b:f646/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:f0:59:09 brd ff:ff:ff:ff:ff:ff
    inet 192.168.77.21/24 brd 192.168.77.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet 192.168.77.201/32 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fef0:5909/64 scope link
       valid_lft forever preferred_lft forever
```

The enp0s8 is the real interface use to communicate with others, calico node is running with

```
calicoctl node --ip=192.168.77.21 
```
And there is another similar node which ip is 192.168.77.22, and a calico profile named ```default```

Now we launch some test containers on both nodes
```
Node1# docker -H :2377 run -e CALICO_IP=auto -e CALICO_PROFILE=default -td ubuntu
...
Node2# docker -H :2377 run -e CALICO_IP=auto -e CALICO_PROFILE=default -td ubuntu
```

At last, IP 0.1 0.3 0.4 on Node1, IP 0.5 on Node2
The host route on each nodes:

```
Node1:
default via 10.0.2.2 dev enp0s3  proto static  metric 1024
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
169.254.0.0/16 dev enp0s8  scope link  metric 1003
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.0.1 dev cali6d21ba50fa0  scope link
192.168.0.3 dev cali8a42a2a2fa0  scope link
192.168.0.4 dev calibf0342f8fa0  scope link
192.168.0.5 via 10.0.2.2 dev enp0s3  proto bird
192.168.77.0/24 dev enp0s8  proto kernel  scope link  src 192.168.77.21

Node2:
default via 10.0.2.2 dev enp0s3  proto static  metric 1024
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
169.254.0.0/16 dev enp0s8  scope link  metric 1003
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.0.1 via 10.0.2.2 dev enp0s3  proto bird
192.168.0.3 via 10.0.2.2 dev enp0s3  proto bird
192.168.0.4 via 10.0.2.2 dev enp0s3  proto bird
192.168.0.5 dev cali896898e6fa0  scope link
192.168.77.0/24 dev enp0s8  proto kernel  scope link  src 192.168.77.22
```

Seems it use ```enp0s3``` not calico running interface ```enp0s8```

### PR DESCRIPTION
**Pull request by tomdee**
Potentially fixes #122

### CODE REVIEW

**Comment by tomdee** [comment]
@liljenstolpe Do you have any thoughts on this?

**Comment by tomdee** [comment]
I'd like to get this in today - @spikecurtis WDYT?

I've spoken to @Symmetric and he thinks it looks good.

**Comment by tomdee** [comment]
Passes FV and discussed with @spikecurtis so merging

**Comment by frostynova** [comment]
Hi, all, i don't know if they are related, but after using the image built from the master,  the route point to the new created containers (on other hosts) appeared slowly (about more than 10 secs), and after that, the new route began to appear and disappear in a cycle

Following is the bird.log
```
2015-05-15 07:14:50 <WARN> ...
2015-05-15 07:14:52 <WARN> Netlink: File exists
2015-05-15 07:14:52 <WARN> Netlink: File exists
2015-05-15 07:14:52 <WARN> ...
2015-05-15 07:14:54 <WARN> Netlink: File exists
2015-05-15 07:14:54 <WARN> Netlink: File exists
2015-05-15 07:14:54 <WARN> ...
2015-05-15 07:14:56 <WARN> Netlink: File exists
2015-05-15 07:14:56 <WARN> Netlink: File exists
2015-05-15 07:14:56 <WARN> ...
2015-05-15 07:14:56 <INFO> Reconfiguration requested by SIGHUP
2015-05-15 07:14:56 <INFO> Reconfiguring
2015-05-15 07:14:56 <TRACE> direct1: Reconfigured
2015-05-15 07:14:56 <INFO> Removing protocol bgp1
2015-05-15 07:14:56 <TRACE> bgp1: Shutting down
2015-05-15 07:14:56 <TRACE> bgp1: Shutdown requested
2015-05-15 07:14:56 <TRACE> bgp1: State changed to stop
2015-05-15 07:14:56 <TRACE> bgp1: BGP session closed
2015-05-15 07:14:56 <INFO> Adding protocol bgp1
2015-05-15 07:14:56 <TRACE> bgp1: Initializing
2015-05-15 07:14:56 <TRACE> bgp1: Starting
2015-05-15 07:14:56 <TRACE> bgp1: State changed to start
2015-05-15 07:14:56 <TRACE> bgp1 > removed 192.168.77.0/24 via 192.168.77.22 on enp0s8
2015-05-15 07:14:56 <TRACE> bgp1 > removed [sole] 192.168.0.5/32 via 192.168.77.22 on enp0s8
2015-05-15 07:14:56 <TRACE> bgp1 > removed [sole] 192.168.0.6/32 via 192.168.77.22 on enp0s8
2015-05-15 07:14:56 <TRACE> bgp1: Sending NOTIFICATION(code=6.3)
2015-05-15 07:14:56 <TRACE> bgp1: Down
2015-05-15 07:14:56 <TRACE> bgp1: State changed to down
2015-05-15 07:14:56 <TRACE> bgp1: Started
2015-05-15 07:14:56 <TRACE> bgp1: Connect delayed by 5 seconds
2015-05-15 07:14:56 <INFO> Reconfigured
2015-05-15 07:14:58 <WARN> Netlink: File exists
2015-05-15 07:14:58 <WARN> Netlink: File exists
2015-05-15 07:14:58 <WARN> ...
2015-05-15 07:14:59 <INFO> Reconfiguration requested by SIGHUP
2015-05-15 07:14:59 <INFO> Reconfiguring
2015-05-15 07:14:59 <TRACE> direct1: Reconfigured
2015-05-15 07:14:59 <INFO> Removing protocol bgp1
2015-05-15 07:14:59 <TRACE> bgp1: Shutting down
2015-05-15 07:14:59 <TRACE> bgp1: Shutdown requested
2015-05-15 07:14:59 <TRACE> bgp1: State changed to stop
2015-05-15 07:14:59 <INFO> Adding protocol bgp1
2015-05-15 07:14:59 <TRACE> bgp1: Initializing
2015-05-15 07:14:59 <TRACE> bgp1: Starting
2015-05-15 07:14:59 <TRACE> bgp1: State changed to start
2015-05-15 07:14:59 <TRACE> bgp1: Down
2015-05-15 07:14:59 <TRACE> bgp1: State changed to down
2015-05-15 07:14:59 <TRACE> bgp1: Started
2015-05-15 07:14:59 <TRACE> bgp1: Connect delayed by 5 seconds
2015-05-15 07:14:59 <INFO> Reconfigured
2015-05-15 07:15:00 <WARN> Netlink: File exists
2015-05-15 07:15:00 <WARN> Netlink: File exists
2015-05-15 07:15:00 <WARN> ...
2015-05-15 07:15:02 <WARN> Netlink: File exists
2015-05-15 07:15:02 <WARN> Netlink: File exists
2015-05-15 07:15:02 <WARN> ...
2015-05-15 07:15:03 <TRACE> bgp1: Incoming connection from 192.168.77.22 (port 50185) accepted
2015-05-15 07:15:03 <TRACE> bgp1: Sending OPEN(ver=4,as=64511,hold=240,id=c0a84d15)
2015-05-15 07:15:03 <TRACE> bgp1: Got OPEN(as=64511,hold=240,id=c0a84d16)
2015-05-15 07:15:03 <TRACE> bgp1: Sending KEEPALIVE
2015-05-15 07:15:03 <TRACE> bgp1: Got KEEPALIVE
2015-05-15 07:15:03 <TRACE> bgp1: BGP session established
2015-05-15 07:15:03 <TRACE> bgp1: Connected to table master
2015-05-15 07:15:03 <TRACE> bgp1: State changed to feed
2015-05-15 07:15:03 <TRACE> bgp1 < filtered out 0.0.0.0/0 via 10.0.2.2 on enp0s3
2015-05-15 07:15:03 <TRACE> bgp1 < filtered out 10.0.2.0/24 dev enp0s3
2015-05-15 07:15:03 <TRACE> bgp1 < added 192.168.77.201/32 dev enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < added 192.168.77.0/24 dev enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < filtered out 169.254.0.0/16 dev enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < added 192.168.0.1/32 dev cali5dc06414fac
2015-05-15 07:15:03 <TRACE> bgp1 < added 192.168.0.3/32 dev cali8e4eec5efac
2015-05-15 07:15:03 <TRACE> bgp1 < added 192.168.0.4/32 dev calicd8c30d4fac
2015-05-15 07:15:03 <TRACE> bgp1 < filtered out 172.17.0.0/16 dev docker0
2015-05-15 07:15:03 <TRACE> bgp1: State changed to up
2015-05-15 07:15:03 <TRACE> bgp1: Sending UPDATE
2015-05-15 07:15:03 <TRACE> bgp1: Sending END-OF-RIB
2015-05-15 07:15:03 <TRACE> bgp1: Got UPDATE
2015-05-15 07:15:03 <TRACE> bgp1 > added 192.168.77.0/24 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < rejected by protocol 192.168.77.0/24 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 > added [best] 192.168.0.5/32 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < rejected by protocol 192.168.0.5/32 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 > added [best] 192.168.0.6/32 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1 < rejected by protocol 192.168.0.6/32 via 192.168.77.22 on enp0s8
2015-05-15 07:15:03 <TRACE> bgp1: Got UPDATE
2015-05-15 07:15:03 <TRACE> bgp1: Got END-OF-RIB
2015-05-15 07:15:04 <WARN> Netlink: File exists
2015-05-15 07:15:04 <WARN> Netlink: File exists
2015-05-15 07:15:04 <WARN> ...
2015-05-15 07:15:06 <WARN> Netlink: File exists
2015-05-15 07:15:06 <WARN> Netlink: File exists
2015-05-15 07:15:06 <WARN> ...
2015-05-15 07:15:08 <WARN> Netlink: File exists
2015-05-15 07:15:08 <WARN> Netlink: File exists
2015-05-15 07:15:08 <WARN> ...
```

**Comment by tomdee** [comment]
I suspect this is because the IPs on your physical interfaces overlap with the range configured for calico. By default you get the following
```
./calicoctl.py  pool show
+----------------+
|   IPv4 CIDR    |
+----------------+
| 192.168.0.0/16 |
+----------------+
```

Bird uses this to control which routes it's exporting.

You should be able to resolve your problem by running `calicoctl pool remove` and `calicoctl pool add` with appropriate subnets.

**Comment by frostynova** [comment]
@tomdee i also found this and changed the pool to 172.20.0.0/16, but still in problem

**Pull request merged**
