### PR TITLE
Issue 96: Improve error msgs for calicoctl command failures

### PR DESCRIPTION
**Pull request by robbrockbank**
This pull request is a fix for issue #96 
See issue for details of fix.

### CODE REVIEW

**Comment by tomdee** [comment]
We don't want details of etcd leaking into calicoctl. I think you should define new exceptions in datastore.py and catch those in calicoctl.

At some point we want to move docker bits out of calicoctl into a separate module too, but not just yet.

**Comment by tomdee** [comment]
LGTM other than the one comment above. I'd prefer not to be adding more docker specific code to calicoctl.py but it's OK for now. The etcd point still stands though,

**Comment by robbrockbank** [comment]
Added a generic DatastoreError that is currently just raised after catching an EtcdException (with the message passed through).  Could no doubt do better here though.

Use a decorator to decorate all datastore public methods to handle general exception catching.

**Comment by tomdee** [comment]
That's a lot of decorators. Not sure if this is really the right approach but I think it's fine to merge for now.

**Pull request merged**
