### PR TITLE
Allow interoperability with OpenStack.

### PR DESCRIPTION
**Pull request by plwhite**

### CODE REVIEW

**Comment by plwhite** [comment]
Trivial changes to make OpenStack objects and Docker objects have consistent behaviour.

Not everything working - in particular, there are some fields that are provisioned by OpenStack in rules that calicoctl does not like - but this gets us to the point where I am unblocked.

**Comment by robbrockbank** [comment]
Accidentally terminated the FV run - I'm re-running this now.

**Comment by spikecurtis** [comment]
LGTM.  @robbrockbank can you comment on FV run result?

**Comment by robbrockbank** [comment]
Yup - it looks like it failed.  See FV run 261

http://calicobobcat-jenkins.gulfstream.datcon.co.uk:8080/job/docker-fvs/261/

**Comment by plwhite** [comment]
If you need me to do anything, let me know - I had a quick check of the results, and saw nothing (couldn't find a failing output log, though presumably not looking in the right place).

**Comment by spikecurtis** [comment]
@plwhite Test failure was

```
======================================================================
ERROR: Test that the profile rule update command successfully updates.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/calico/workspace/docker-fvs/calico_containers/tests/st/test_profile_commands.py", line 28, in test_profile_commands
    host.calicoctl("profile TEST_PROFILE tag add TEST_TAG")
  File "/home/calico/workspace/docker-fvs/calico_containers/tests/st/docker_host.py", line 78, in calicoctl
    return self.execute(calicoctl % command, **kwargs)
  File "/home/calico/workspace/docker-fvs/calico_containers/tests/st/docker_host.py", line 71, in execute
    return self._listen(stdin, **kwargs)
  File "/home/calico/workspace/docker-fvs/calico_containers/tests/st/docker_host.py", line 54, in _listen
    "bash", s=True, _in=stdin, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 486, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
ErrorReturnCode_1: 

  RAN: '/usr/bin/docker exec --interactive host bash -s'

  STDOUT:
Tags names can only contain numbers, letters, dots, dashes and underscores.



  STDERR:
```

I suspect your new regex for tags is bugged and only matches single character tags.

**Comment by plwhite** [comment]
Doh - thanks Spike. I've fixed that issue and repushed, will see if the tests run clean this time.

**Comment by plwhite** [comment]
I'm puzzled - looks from the console output like build_node.sh is failing, presumably from the output with an error returned by pip install, but it works for me on a clean checkout, which means that I'm a bit lost trying to figure it out.

**Comment by robbrockbank** [comment]
Looks like the code needed a rebase to pick up a change with one of the image locations.  I'll merge.

**Pull request merged**
